import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Emerald Canopy Design System
        "primary": "#005237",
        "primary-container": "#006d4a",
        "on-primary": "#ffffff",
        "on-primary-container": "#94ecbf",
        "primary-fixed": "#9cf5c8",
        "primary-fixed-dim": "#81d8ad",
        "secondary": "#006c49",
        "secondary-container": "#6cf8ba",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714c",
        "secondary-fixed": "#6ffbbd",
        "secondary-fixed-dim": "#4edea2",
        "tertiary": "#79302d",
        "tertiary-container": "#974743",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffcfcb",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ae",
        "surface": "#f7faf5",
        "surface-dim": "#d8dbd6",
        "surface-bright": "#f7faf5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4ef",
        "surface-container": "#ecefea",
        "surface-container-high": "#e6e9e4",
        "surface-container-highest": "#e0e3df",
        "surface-variant": "#e0e3df",
        "on-surface": "#181c1a",
        "on-surface-variant": "#3f4943",
        "background": "#f7faf5",
        "on-background": "#181c1a",
        "outline": "#6f7a72",
        "outline-variant": "#bec9c0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d312e",
        "inverse-on-surface": "#eff2ed",
        "inverse-primary": "#81d8ad",
        "surface-tint": "#006c49",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#3e0406",
        "on-tertiary-fixed-variant": "#782f2d",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "ambient": "0 40px 60px rgba(0, 82, 55, 0.05)",
        "ambient-md": "0 20px 40px rgba(0, 82, 55, 0.08)",
        "ambient-lg": "0 40px 60px rgba(0, 82, 55, 0.12)",
        "primary-glow": "0 12px 40px rgba(0, 82, 55, 0.15)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
